# Generated by Django 2.0.4 on 2018-07-11 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='菜单名')),
                ('href', models.CharField(default='#', max_length=30, verbose_name='链接地址')),
                ('slug', models.SlugField(max_length=40, verbose_name='slug')),
                ('parent_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.Menu', verbose_name='父级菜单')),
            ],
            options={
                'verbose_name': '菜单设置',
                'verbose_name_plural': '菜单设置',
                'ordering': ['name'],
            },
        ),
    ]
