# Generated by Django 2.0.4 on 2018-07-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companycode', models.CharField(max_length=10)),
                ('companyabb', models.CharField(max_length=10)),
                ('stockexchangeno', models.CharField(max_length=10)),
                ('stockstyle', models.CharField(max_length=10)),
                ('stockcode', models.CharField(max_length=10)),
                ('stockabb', models.CharField(max_length=10)),
                ('listingdate', models.DateField(null=True)),
                ('generalcapital', models.FloatField()),
                ('circulatingcapital', models.FloatField()),
                ('bysector', models.CharField(max_length=10)),
                ('filename', models.CharField(max_length=10, null=True)),
                ('startdate', models.DateField(null=True)),
                ('enddate', models.DateField(null=True)),
                ('path', models.CharField(max_length=50, null=True)),
                ('fupdatetime', models.DateField(null=True)),
            ],
            options={
                'permissions': (('views_name_manage', '名称管理'),),
            },
        ),
    ]
