# Generated by Django 2.0.4 on 2018-07-15 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20180711_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='pricedaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('tclose', models.FloatField(null=True)),
                ('high', models.FloatField(null=True)),
                ('low', models.FloatField(null=True)),
                ('topen', models.FloatField(null=True)),
                ('lclose', models.FloatField(null=True)),
                ('chg', models.FloatField(null=True)),
                ('pchg', models.FloatField(null=True)),
                ('voturnover', models.FloatField(null=True)),
                ('vaturnover', models.FloatField(null=True)),
            ],
            options={
                'verbose_name': '每日价格',
                'verbose_name_plural': '每日价格',
                'permissions': (('views_price_data_manage', '价格数据管理'),),
            },
        ),
        migrations.AlterModelOptions(
            name='name',
            options={'permissions': (('views_name_manage', '名称管理'),), 'verbose_name': '股票名称', 'verbose_name_plural': '股票名称'},
        ),
        migrations.AddField(
            model_name='pricedaily',
            name='stockname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Name'),
        ),
    ]
