# Generated by Django 2.0.4 on 2018-07-17 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20180715_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='name',
            name='path',
        ),
    ]
