# Generated by Django 2.0.4 on 2018-07-20 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_remove_name_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bigexchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('zhulj', models.FloatField(null=True)),
                ('zhuljper', models.FloatField(null=True)),
                ('chaodd', models.FloatField(null=True)),
                ('chaoddper', models.FloatField(null=True)),
                ('dd', models.FloatField(null=True)),
                ('ddper', models.FloatField(null=True)),
                ('zd', models.FloatField(null=True)),
                ('zdper', models.FloatField(null=True)),
                ('xd', models.FloatField(null=True)),
                ('xdper', models.FloatField(null=True)),
                ('stockname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Name')),
            ],
            options={
                'verbose_name': '大单交易',
                'verbose_name_plural': '大单交易',
                'permissions': (('views_dd_data_manage', '大单数据管理'), ('views_k_unit_manage', '曲线对比')),
            },
        ),
    ]
