# Generated by Django 2.0.4 on 2018-07-08 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='归类'),
        ),
    ]
