# Generated by Django 2.0.4 on 2018-07-11 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180710_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': '博客分类', 'verbose_name_plural': '博客分类'},
        ),
    ]
