# Generated by Django 2.0.4 on 2018-07-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['name'], 'verbose_name': '菜单设置', 'verbose_name_plural': '菜单设置'},
        ),
        migrations.AlterField(
            model_name='menu',
            name='href',
            field=models.CharField(default='#', max_length=30, verbose_name='链接地址'),
        ),
    ]
